### ISSUE TITLE
[Fault] attempt to call method 'SendShowMailbox' silently fails

### ISSUE THREAD

**Issue by DrKittens** [Niam5/Eluna#2]
Steps to Reproduce:

1. Add this script to lua scripts folder as testaccount.lua
```lua
--Do .testmailcmd to invoke
local PLAYER_EVENT_ON_COMMAND = 42

function testcommand(event, player, command)
--Wheres the player @
   local x, y, z, o = player:GetLocation()
--Drop a mailbox on my head
   local mailbox = player:SummonGameObject(142075, (x), (y), z, o) --142075 is a mailbox, right clicking it works
   player:SendShowMailbox(mailbox:GetGUID())
   player:SendShowMailbox(mailbox:GetGUIDLow())
   player:SendShowMailbox(player:GetGUIDLow())
end

RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, testcommand)
```

2. restart mangosd / reload eluna

Expected Behaviour: 
One of the varients of SendShowMailbox actually opens the mailbox window

What Actually Happens:
3 repeats of the ``attempt to call method 'SendShowMailbox' (a nil value)`` error in console

Functional use of this method is here: (scenario doesnt work in cmangos, but author advises functional)
https://github.com/brandon4650/Charity_lua/blob/7ff089f5634ec12ec7565e16daec31343dfc7e6f/charity.lua#L59
https://github.com/brandon4650/Charity_lua/blob/7ff089f5634ec12ec7565e16daec31343dfc7e6f/charity.lua#L84

```lua
--super shorthand
local function OnGossipHello(event, player, object)
    local playerGUID = player:GetGUIDLow()
    player:SendShowMailBox(playerGUID)
end

**Comment by DrKittens** [comment]
After ammending SendShowMailbox to SendShowMail**B**ox

The below errors silently / does not display the expected screen
```lua
--Do .testmailcmd to invoke
local PLAYER_EVENT_ON_COMMAND = 42

function testcommand(event, player, command)
--Wheres the player @
   local x, y, z, o = player:GetLocation()
--Drop a mailbox on my head
   local mailbox = player:SummonGameObject(142075, (x), (y), z, o) --142075 is a mailbox, right clicking it works
   player:SendShowMailbox(mailbox:GetGUID())
   player:SendShowMailbox(mailbox:GetGUIDLow())
   player:SendShowMailbox(player:GetGUIDLow())
   player:SendShowMailbox(player:GetGUID())
end

RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, testcommand)
```

**Comment by Niam5** [comment]
SendShowMailBox calls a core method to update the mail list in an already opened mailbox window. The client opens this window when a gameobject of type 19 is interacted with, the client sends a CMSG that trigger the core function and the server return the contents that should be displayed in an SMSG. Only in WotLK did a new SMSG get introduced that allowed the server to tell the client to open a mailbox window. There is no way to make any prior client do this as its all client side to open the window.

Closing as unfixable for classic and TBC
