### ISSUE TITLE
I am a beginner,could you please update vmangos branch page?

### ISSUE THREAD

**Issue by leechunlung** [Niam5/Eluna#4]
I am a beginner. Could you please update this branch page：
https://github.com/Niam5/VMangos-eluna
God praises you!

**Comment by Niam5** [comment]
I redid the repository a bit but I have not updated it to the latest Eluna(multistate) that is going to take a bit of doing so it has been held back. New repo is here https://github.com/Niam5/Eluna-VMaNGOS
